version: '3.8'

services:
  database:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: quotes
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
